### ISSUE TITLE
need update!!! error button = driver.find_element_by_css_selector(button_css)

### ISSUE THREAD

**Issue by chourete** [firebfm/deepl-srt#4]
It can be used normally before,
But not anymore
please!?

Traceback (most recent call last):
File "deeplv4.py", line 185, in
content = paste_it(chunk)
File "deeplv4.py", line 88, in paste_it
button = driver.find_element_by_css_selector(button_css)
File "C:\Users\RX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\selenium\webdriver\remote\webdriver.py", line 598, in find_element_by_css_selector
return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
File "C:\Users\RX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
'value': value})['value']
File "C:\Users\RX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
self.error_handler.check_response(response)
File "C:\Users\RX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":" div.lmt__target_toolbar__copy button"}
(Session info: chrome=94.0.4606.71)

**Comment by chourete** [comment]
just change button_css can fix it
button_css = 'div.lmt__target_toolbar__copy_container button'

but
But whenever the ninth translation (chunk 9), deepl will be timeout, and python will stop(error),maybe need some delay time?
@firebfm

**Comment by bk111** [comment]
thanks. now it's ok
